### ISSUE TITLE
Új temető létrehozásakor SQL error

### ISSUE THREAD

**Issue by gaborpfeiffer** [Danes90/cm#2]
**Message:**

> "SQLSTATE[HY000]: General error: 1364 Field 'image' doesn't have a default value (SQL: insert into `cemeteries` (`title`, `address`, `updated_at`, `created_at`) values (Teszt, Teszt cím, 2019-10-03 21:04:56, 2019-10-03 21:04:56))"

**Comment by Danes90** [comment]
atabase/migrations/2019_09_24_152400_create_cemeteries_table.php 20 sor image, majd azt kikommentezem és pusholom
